# Generated by Django 5.0.6 on 2024-05-22 17:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prog_language_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("blog_snippet", models.TextField()),
                (
                    "categories",
                    models.ManyToManyField(related_name="posts", to="website.category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "descritption",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("project_url", models.URLField(max_length=255, null=True)),
                (
                    "languages",
                    models.ManyToManyField(
                        null=True, related_name="projects", to="website.language"
                    ),
                ),
            ],
        ),
    ]
